/**
 * gesteZones.js
 * Mapping clé-de-geste → { view, zone }
 *   view : 'interior' | 'exterior'
 *   zone : identifiant de zone dans CarDiagram.jsx
 */

export const GESTURE_ZONES = {
  // ── Intérieur ────────────────────────────────────────────────────
  'actionner-feux-detresse':          { view: 'interior', zone: 'hazard-button' },
  'air-pare-brise':                   { view: 'interior', zone: 'climate-controls' },
  'allumer-brouillard-arriere':       { view: 'interior', zone: 'stalk-left' },
  'allumer-feux-route':               { view: 'interior', zone: 'stalk-left' },
  'attestation-assurance':            { view: 'interior', zone: 'documents' },
  'avertisseur-sonore':               { view: 'interior', zone: 'steering-wheel' },
  'certificat-immatriculation':       { view: 'interior', zone: 'documents' },
  'constat-amiable':                  { view: 'interior', zone: 'documents' },
  'degivrage-lunette-arriere':        { view: 'interior', zone: 'dash-center' },
  'desactivation-airbag':             { view: 'interior', zone: 'left-lower-dash' },
  'essuie-glace-arriere':             { view: 'interior', zone: 'stalk-right' },
  'essuie-glaces-avant':              { view: 'interior', zone: 'stalk-right' },
  'ethylotest':                       { view: 'interior', zone: 'documents' },
  'feux-brouillard-arriere-controle': { view: 'interior', zone: 'instrument-cluster' },
  'feux-croisement':                  { view: 'interior', zone: 'stalk-left' },
  'feux-detresse-controle':           { view: 'interior', zone: 'instrument-cluster' },
  'feux-diurnes':                     { view: 'interior', zone: 'stalk-left' },
  'feux-position':                    { view: 'interior', zone: 'stalk-left' },
  'feux-recul':                       { view: 'interior', zone: 'gear-lever' },
  'feux-route-controle':              { view: 'interior', zone: 'instrument-cluster' },
  'feux-stop':                        { view: 'interior', zone: 'brake-pedal' },
  'gilet-visibilite':                 { view: 'interior', zone: 'documents' },
  'indicateur-carburant':             { view: 'interior', zone: 'instrument-cluster' },
  'isofix':                           { view: 'interior', zone: 'rear-seat' },
  'limiteur-vitesse':                 { view: 'interior', zone: 'speed-controls' },
  'recyclage-air':                    { view: 'interior', zone: 'climate-controls' },
  'reglage-appui-tete':               { view: 'interior', zone: 'headrest' },
  'reglage-hauteur-feux':             { view: 'interior', zone: 'left-lower-dash' },
  'reglage-volant':                   { view: 'interior', zone: 'steering-column' },
  'regulateur-vitesse':               { view: 'interior', zone: 'speed-controls' },
  'retroviseur-nuit':                 { view: 'interior', zone: 'rearview-mirror' },
  'securite-enfant':                  { view: 'interior', zone: 'door-panel' },
  'triangle-presignalisation':        { view: 'interior', zone: 'documents' },
  'voyant-ceinture':                  { view: 'interior', zone: 'instrument-cluster' },
  'voyant-defaut-batterie':           { view: 'interior', zone: 'instrument-cluster' },
  'voyant-portiere':                  { view: 'interior', zone: 'instrument-cluster' },
  'voyant-pression-huile':            { view: 'interior', zone: 'instrument-cluster' },
  'voyant-pression-pneu':             { view: 'interior', zone: 'instrument-cluster' },
  'voyant-temperature':               { view: 'interior', zone: 'instrument-cluster' },

  // ── Extérieur ────────────────────────────────────────────────────
  'ampoule-arriere':                  { view: 'exterior', zone: 'rear-lights' },
  'ampoule-avant':                    { view: 'exterior', zone: 'front-lights' },
  'balais-essuie-glace':              { view: 'exterior', zone: 'windshield' },
  'capot-ouverture':                  { view: 'exterior', zone: 'hood' },
  'clignotants-trottoir':             { view: 'exterior', zone: 'turn-signal' },
  'coffre-ouverture':                 { view: 'exterior', zone: 'trunk' },
  'dispositifs-reflechissants':       { view: 'exterior', zone: 'reflectors' },
  'eclairage-plaque':                 { view: 'exterior', zone: 'license-plate' },
  'emplacement-batterie':             { view: 'exterior', zone: 'hood' },
  'flanc-pneu':                       { view: 'exterior', zone: 'front-wheel' },
  'gicleurs-lave-glace':              { view: 'exterior', zone: 'windshield' },
  'niveau-huile-moteur':              { view: 'exterior', zone: 'hood' },
  'niveau-liquide-frein':             { view: 'exterior', zone: 'hood' },
  'plaque-pression-pneu':             { view: 'exterior', zone: 'front-wheel' },
  'plaques-immatriculation':          { view: 'exterior', zone: 'license-plate-front' },
  'remplissage-huile':                { view: 'exterior', zone: 'hood' },
  'remplissage-lave-glace':           { view: 'exterior', zone: 'hood' },
  'remplissage-refroidissement':      { view: 'exterior', zone: 'hood' },
  'temoin-usure-pneu':                { view: 'exterior', zone: 'front-wheel' },
  'trappe-carburant':                 { view: 'exterior', zone: 'fuel-cap' },
}

// Zone labels (affichés comme indicateur sous le schéma)
export const ZONE_LABELS = {
  // Interior
  'rearview-mirror':    'Rétroviseur intérieur',
  'instrument-cluster': 'Tableau de bord — voyants',
  'stalk-left':         'Commodo gauche (feux)',
  'stalk-right':        'Commodo droit (essuie-glaces)',
  'steering-wheel':     'Volant',
  'steering-column':    'Colonne de direction',
  'left-lower-dash':    'Panneau gauche — réglage feux / airbag',
  'dash-center':        'Tableau de bord central',
  'hazard-button':      'Bouton feux de détresse',
  'climate-controls':   'Commandes climatisation',
  'speed-controls':     'Limiteur / Régulateur vitesse',
  'headrest':           'Appui-tête',
  'passenger-area':     'Zone passager / Airbag',
  'door-panel':         'Panneau de porte conducteur',
  'documents':          'Boîte à gants / Documents de bord',
  'rear-seat':          'Siège arrière / ISOFIX',
  'center-console':     'Console centrale',
  'gear-lever':         'Levier de vitesse',
  'brake-pedal':        'Pédalier (frein)',
  // Exterior
  'hood':               'Capot / Compartiment moteur',
  'front-lights':       'Feux avant',
  'windshield':         'Pare-brise / Essuie-glaces',
  'front-wheel':        'Roue avant / Pneu',
  'rear-wheel':         'Roue arrière / Pneu',
  'fuel-cap':           'Trappe carburant',
  'trunk':              'Coffre',
  'rear-lights':        'Feux arrière',
  'license-plate':      'Plaque arrière',
  'license-plate-front':'Plaque avant',
  'turn-signal':        'Clignotant côté trottoir',
  'reflectors':         'Dispositifs réfléchissants',
}
